### ISSUE TITLE
adapters remains after using NGmerge

### ISSUE THREAD

**Issue by tothuhien** [jsh58/NGmerge#6]
Hello,
I’ve just tried to use NGmerge to cut the adapter from about paired-end data. Fastqc Report shows that  Nextera Transposase Sequence is the adapter (Fig1).
I use NGmerge to cut the adapter with the following command:
NGmerge/NGmerge -z -a -1 R1.fastq.gz -2 R2.fastq.gz -o cut_R
But the cut file still contains some adapters (Fig2)
Do you have any idea about that? Did I use it properly?
Thank you very much
Hien
![Fig1](https://user-images.githubusercontent.com/14748898/57301376-2ad00200-70d9-11e9-9daf-de8b6a41d16b.png)
![Fig2](https://user-images.githubusercontent.com/14748898/57301381-2dcaf280-70d9-11e9-9415-4bd5622899ee.png)

**Comment by jsh58** [comment]
Hien,

Thanks for the question, and for including the graphs.  It appears that your library had some *very* short fragments, with adapters starting to appear around base 30.  Therefore, you should adjust the [`-e` parameter](https://github.com/jsh58/NGmerge#stitch-aln):
> -e  &lt;int&gt;        Minimum overlap of dovetailed alignments (def. 50)
This is the minimum overlap length (in bp) for alignments with 3' overhangs (see Fig. 2B). This value should be set to the length of the absolute shortest DNA fragment that may have been sequenced.

You should decrease this value to, e.g., `-e 30`.  The default value is 50, which is why in your second graph the curve flattens out after 50bp.

John Gaspar

**Comment by tothuhien** [comment]
Thanks for your quick response, I understand the problem now. I've tried your suggestion and it works now! Could I ask another question? Is it ok if I set this value too low, for example 10, because I'm not sure about the length of shortest fragments. Could it make any effect on the results?
Thanks in advance.

**Comment by jsh58** [comment]
I guess I shouldn't have cut off the [parameter description](https://github.com/jsh58/NGmerge#stitch-aln):
>  -e  &lt;int&gt;        Minimum overlap of dovetailed alignments (def. 50)
This is the minimum overlap length (in bp) for alignments with 3' overhangs (see Fig. 2B). This value should be set to the length of the absolute shortest DNA fragment that may have been sequenced. Using a value that is too low may result in false positives, especially if the reads contain repetitive sequences.

**Comment by tothuhien** [comment]
Thanks a lot! I should have had read the user guide carefully.
Cheers.
